#!/bin/sh

# Using stdout for logging
# Using control/defaultdelivery from qmail-local to deliver messages by default

exec \
    env - PATH="/var/qmail/bin:$PATH" \
    /usr/bin/softlimit -m 10000000 \
    qmail-start "$(cat /var/qmail/control/defaultdelivery)"

