#!/bin/bash

set -e
set -u
set -o pipefail

QMAILDUID=$(id -u qmaild)
NOFILESGID=$(id -g qmaild)
MAXSMTPD=$(cat /var/qmail/control/concurrencyincoming || echo 50)
LOCAL=$(head -1 /var/qmail/control/me)

if [ -z "$QMAILDUID" -o -z "$NOFILESGID" -o -z "$MAXSMTPD" -o \
     -z "$LOCAL" ]; then
  echo QMAILDUID, NOFILESGID, MAXSMTPD, or LOCAL are unset
  exit 1
fi

if [ ! -f /var/qmail/control/rcpthosts ]; then
  echo "No /var/qmail/control/rcpthosts!"
  echo "Refusing to start SMTP listener because it'll create an open relay"
  exit 1
fi

exec \
  env \
    - \
    CHECKENV="" \
    CVM_CHAIN0=cvm-pwfile \
    CVM_CHAIN1=cvm-unix \
    CVM_PWFILE_PATH=/var/qmail/control/passwd \
    CVM_PWFILE_PWCMP=crypt \
    PATH="/var/qmail/bin:$PATH" \
    SMTPAUTH="${SMTPAUTH:-}" \
    TLSCIPHERS="HIGH:!aNULL:!eNULL@STRENGTH" \
    softlimit \
      -m 100000000 \
      tcpserver \
        -v \
        -R \
        -l "$LOCAL" \
        -x /etc/tcp.smtp.cdb \
        -c "$MAXSMTPD" \
        -u "$QMAILDUID" \
        -g "$NOFILESGID" \
        0 \
        ${PORT:-smtp} \
        /var/qmail/bin/qmail-smtpd \
          /usr/bin/cvm-checkpassword /usr/bin/cvm-chain true 2>&1

