#!/bin/bash

QMAILDUID=`id -u qmaild`
NOFILESGID=`id -g qmaild`
MAXSMTPD=`cat /var/qmail/control/concurrencyincoming`
LOCAL=`head -1 /var/qmail/control/me`

export SMTPAUTH="${SMTPAUTH:-}"
export CHECKENV=""

if [ -z "$QMAILDUID" -o -z "$NOFILESGID" -o -z "$MAXSMTPD" -o -z "$LOCAL" ]; then
  echo QMAILDUID, NOFILESGID, MAXSMTPD, or LOCAL is unset in
  echo /var/qmail/supervise/qmail-smtpd/run
  exit 1
fi

if [ ! -f /var/qmail/control/rcpthosts ]; then
  echo "No /var/qmail/control/rcpthosts!"
  echo "Refusing to start SMTP listener because it'll create an open relay"
  exit 1
fi

exec \
  /usr/bin/softlimit \
    -m 25000000 \
    /usr/bin/tcpserver \
      -v \
      -R \
      -l "$LOCAL" \
      -x /etc/tcp.smtp.cdb \
      -c "$MAXSMTPD" \
      -u "$QMAILDUID" \
      -g "$NOFILESGID" \
      0 \
      ${PORT:-smtp} \
      /var/qmail/bin/qmail-greyd \
        /usr/bin/rblsmtpd -r zen.spamhaus.org \
          /var/qmail/bin/qmail-smtpd /usr/bin/cvm-checkpassword cvm-unix true 2>&1

